import {
  IconArticle,
  IconBook,
  IconBrandAdobePhotoshop,
  IconBrandAndroid,
  IconBrandChrome,
  IconBrandDebian,
  IconBrandRedhat,
  IconBrandWindows,
  IconCertificate,
  IconContract,
  IconDatabase,
  IconDeviceGamepad,
  IconFavicon,
  IconFileDigit,
  IconFileSettings,
  IconFileSpreadsheet,
  IconFileTypeBmp,
  IconFileTypeCss,
  IconFileTypeCsv,
  IconFileTypeHtml,
  IconFileTypeJpg,
  IconFileTypeJs,
  IconFileTypePdf,
  IconFileTypePng,
  IconFileTypePpt,
  IconFileTypeSvg,
  IconFileTypeTxt,
  IconFileTypeXml,
  IconFileTypeZip,
  IconFileTypography,
  IconFileWord,
  IconFileZip,
  IconGif,
  IconHeartRateMonitor,
  IconJson,
  IconMovie,
  IconMusic,
  IconPhoto,
  IconScript,
} from "@tabler/icons-react";

export enum FsVariant {
  File = "File",
  Dir = "Dir",
}

export enum FileType {
  // Image
  Jpg = "image/jpeg",
  Png = "image/png",
  Gif = "image/gif",
  Webp = "image/webp",
  Cr2 = "image/x-canon-cr2",
  Tif = "image/tiff",
  Bmp = "image/bmp",
  Heif = "image/heif",
  Avif = "image/avif",
  Jxr = "image/vnd.ms-photo",
  Psd = "image/vnd.adobe.photoshop",
  Ico = "image/vnd.microsoft.icon",
  Ora = "image/openraster",
  Djvu = "image/vnd.djvu",
  Svg = "image/svg+xml",

  // Video
  Mp4 = "video/mp4",
  M4v = "video/x-m4v",
  Mkv = "video/x-matroska",
  Webm = "video/webm",
  Mov = "video/quicktime",
  Avi = "video/x-msvideo",
  Wmv = "video/x-ms-wmv",
  Mpg = "video/mpeg",
  Flv = "video/x-flv",

  // Audio
  Mid = "audio/midi",
  Mp3 = "audio/mpeg",
  M4a = "audio/m4a",
  Ogg = "audio/ogg",
  Flac = "audio/x-flac",
  Wav = "audio/x-wav",
  Amr = "audio/amr",
  Aac = "audio/aac",
  Aiff = "audio/x-aiff",
  Dsf = "audio/x-dsf",
  Ape = "audio/x-ape",

  // Archive
  Zip = "application/zip",
  Tar = "application/x-tar",
  Rar = "application/vnd.rar",
  Rar2 = "application/x-rar-compressed",
  Gz = "application/gzip",
  Bz2 = "application/x-bzip2",
  Z7 = "application/x-7z-compressed",
  Xz = "application/x-xz",
  Pdf = "application/pdf",
  Swf = "application/x-shockwave-flash",
  Rtf = "application/rtf",
  Eot = "application/octet-stream",
  Ps = "application/postscript",
  Sqlite = "application/vnd.sqlite3",
  Nes = "application/x-nintendo-nes-rom",
  Crx = "application/x-google-chrome-extension",
  Cab = "application/vnd.ms-cab-compressed",
  Deb = "application/vnd.debian.binary-package",
  Ar = "application/x-unix-archive",
  Z = "application/x-compress",
  Lz = "application/x-lzip",
  Rpm = "application/x-rpm",
  Dcm = "application/dicom",
  Zst = "application/zstd",
  Msi = "application/x-ole-storage",
  Cpio = "application/x-cpio",

  // Book
  Epub = "application/epub+zip",
  Mobi = "application/x-mobipocket-ebook",

  // Documents
  Doc = "application/msword",
  Docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  Xls = "application/vnd.ms-excel",
  Xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  Ppt = "application/vnd.ms-powerpoint",
  Pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  Odt = "application/vnd.oasis.opendocument.text",
  Ods = "application/vnd.oasis.opendocument.spreadsheet",
  Odp = "application/vnd.oasis.opendocument.presentation",
  Csv = "text/csv",

  // Font
  Woff = "application/font-woff",
  Woff2 = "application/font-woff2",
  Ttf = "application/font-sfnt",
  Otf = "application/x-font-opentype",

  // Application
  Wasm = "application/wasm",
  Exe = "application/vnd.microsoft.portable-executable",
  Dll = "application/x-msdownload",
  Elf = "application/x-executable",
  Bc = "application/llvm",
  Mach = "application/x-mach-binary",
  Class = "application/java",
  Dex = "application/vnd.android.dex",
  Dey = "application/vnd.android.dey",
  Der = "application/x-x509-ca-cert",
  Obj = "application/object",

  // Other
  Json = "application/json",
  Xml = "text/xml",
  Html = "text/html",
  Css = "text/css",
  Js = "text/javascript",
  Txt = "text/plain",
}

export const FileTypeIcon = {
  // Image
  [FileType.Jpg]: IconFileTypeJpg,
  [FileType.Png]: IconFileTypePng,
  [FileType.Gif]: IconGif,
  [FileType.Webp]: IconPhoto,
  [FileType.Cr2]: IconPhoto,
  [FileType.Tif]: IconPhoto,
  [FileType.Bmp]: IconFileTypeBmp,
  [FileType.Heif]: IconPhoto,
  [FileType.Avif]: IconPhoto,
  [FileType.Jxr]: IconPhoto,
  [FileType.Psd]: IconBrandAdobePhotoshop,
  [FileType.Ico]: IconFavicon,
  [FileType.Ora]: IconPhoto,
  [FileType.Djvu]: IconPhoto,
  [FileType.Svg]: IconFileTypeSvg,

  // Video
  [FileType.Mp4]: IconMovie,
  [FileType.M4v]: IconMovie,
  [FileType.Mkv]: IconMovie,
  [FileType.Webm]: IconMovie,
  [FileType.Mov]: IconMovie,
  [FileType.Avi]: IconMovie,
  [FileType.Wmv]: IconMovie,
  [FileType.Mpg]: IconMovie,
  [FileType.Flv]: IconMovie,

  // Audio
  [FileType.Mid]: IconMusic,
  [FileType.Mp3]: IconMusic,
  [FileType.M4a]: IconMusic,
  [FileType.Ogg]: IconMusic,
  [FileType.Flac]: IconMusic,
  [FileType.Wav]: IconMusic,
  [FileType.Amr]: IconMusic,
  [FileType.Aac]: IconMusic,
  [FileType.Aiff]: IconMusic,
  [FileType.Dsf]: IconMusic,
  [FileType.Ape]: IconMusic,

  // Archieve
  [FileType.Zip]: IconFileTypeZip,
  [FileType.Tar]: IconFileZip,
  [FileType.Rar]: IconFileZip,
  [FileType.Rar2]: IconFileZip,
  [FileType.Gz]: IconFileZip,
  [FileType.Bz2]: IconFileZip,
  [FileType.Z7]: IconFileZip,
  [FileType.Xz]: IconFileZip,
  [FileType.Pdf]: IconFileTypePdf,
  [FileType.Swf]: IconScript,
  [FileType.Rtf]: IconArticle,
  [FileType.Eot]: IconContract,
  [FileType.Ps]: IconBrandAdobePhotoshop,
  [FileType.Sqlite]: IconDatabase,
  [FileType.Nes]: IconDeviceGamepad,
  [FileType.Crx]: IconBrandChrome,
  [FileType.Cab]: IconFileZip,
  [FileType.Deb]: IconBrandDebian,
  [FileType.Ar]: IconFileZip,
  [FileType.Z]: IconFileZip,
  [FileType.Lz]: IconFileZip,
  [FileType.Rpm]: IconBrandRedhat,
  [FileType.Dcm]: IconHeartRateMonitor,
  [FileType.Zst]: IconFileZip,
  [FileType.Msi]: IconBrandWindows,
  [FileType.Cpio]: IconFileZip,

  // Book
  [FileType.Epub]: IconBook,
  [FileType.Mobi]: IconBook,

  // Documents
  [FileType.Doc]: IconFileWord,
  [FileType.Docx]: IconFileWord,
  [FileType.Xls]: IconFileSpreadsheet,
  [FileType.Xlsx]: IconFileSpreadsheet,
  [FileType.Ppt]: IconFileTypePpt,
  [FileType.Pptx]: IconFileTypePpt,
  [FileType.Odt]: IconFileWord,
  [FileType.Ods]: IconFileSpreadsheet,
  [FileType.Odp]: IconFileTypePpt,
  [FileType.Csv]: IconFileTypeCsv,

  // Font
  [FileType.Woff]: IconFileTypography,
  [FileType.Woff2]: IconFileTypography,
  [FileType.Ttf]: IconFileTypography,
  [FileType.Otf]: IconFileTypography,

  // Application
  [FileType.Wasm]: IconFileDigit,
  [FileType.Exe]: IconBrandWindows,
  [FileType.Dll]: IconFileSettings,
  [FileType.Elf]: IconBrandWindows,
  [FileType.Bc]: IconFileDigit,
  [FileType.Mach]: IconFileDigit,
  [FileType.Class]: IconScript,
  [FileType.Dex]: IconBrandAndroid,
  [FileType.Dey]: IconBrandAndroid,
  [FileType.Der]: IconCertificate,
  [FileType.Obj]: IconScript,

  // Other
  [FileType.Json]: IconJson,
  [FileType.Xml]: IconFileTypeXml,
  [FileType.Html]: IconFileTypeHtml,
  [FileType.Css]: IconFileTypeCss,
  [FileType.Js]: IconFileTypeJs,
  [FileType.Txt]: IconFileTypeTxt,
};

export const FileTypeColors = {
  // Archive
  [FileType.Pdf]: "#d1001f",
  [FileType.Ps]: "#1971c2",

  // Documents
  [FileType.Doc]: "#1480d8",
  [FileType.Docx]: "#1480d8",
  [FileType.Xls]: "#1d6f42",
  [FileType.Xlsx]: "#1d6f42",
  [FileType.Ppt]: "#dc3e15",
  [FileType.Pptx]: "#dc3e15",
  [FileType.Odt]: "#1480d8",
  [FileType.Ods]: "#1d6f42",
  [FileType.Odp]: "#dc3e15",
  [FileType.Csv]: "#1d6f42",

  // Other
  [FileType.Json]: "#ff922b",
  [FileType.Html]: "#f06529",
  [FileType.Css]: "#2695f1",
  [FileType.Js]: "#f0db4f",
};

export enum FsType {
  File = "file",
  Folder = "folder",
}
